# Generated by Django 4.2.3 on 2023-07-29 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=50, null=True)),
                ('volume', models.IntegerField()),
                ('type', models.CharField(choices=[('vo', 'vo'), ('bg_music', 'bg_music'), ('video_music', 'video_music')], max_length=50)),
                ('video_component_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startTime', models.IntegerField()),
                ('endTime', models.IntegerField()),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.audiomodel')),
            ],
        ),
    ]
